### ISSUE TITLE
what's the difference between the qemu here and the community one??

### ISSUE THREAD

**Issue by moypray** [Xilinx/qemu#10]
thanks~~

**Comment by alistair23** [comment]
Hello moypray,

There are quite a few differences between the Xilinx QEMU and the mainline QEMU. Xilinx recommends that you use the Xilinx QEMU as it has better support for our products. Some of the key features that the Xilinx QEMU repo has compared to the mainline repo are:
 - FDT Generic (Automatically generate machines from the device tree)
 - Improved MicroBlaze, Zynq and ZynqMP support
 - Support for more Xilinx peripherals
    - Including Display Port and the PMU
 - Improved ARMv8 EL support
 - Device loading improvements targeted for ZynqMP

Thanks,

Alistair

**Comment by alistair23** [comment]
Hello moypray,

There are quite a few differences between the Xilinx QEMU and the mainline QEMU. Xilinx recommends that you use the Xilinx QEMU as it has better support for our products. Some of the key features that the Xilinx QEMU repo has compared to the mainline repo are:
 - FDT Generic (Automatically generate machines from the device tree)
 - Improved MicroBlaze, Zynq and ZynqMP support
 - Support for more Xilinx peripherals
    - Including Display Port and the PMU
 - Improved ARMv8 EL support
 - Device loading improvements targeted for ZynqMP

Thanks,

Alistair

**Comment by moypray** [comment]
@alistair23 , Got it, thanks for your information~~
