### ISSUE TITLE
 Xilinx Qemu user mode emulation

### ISSUE THREAD

**Issue by ddresser** [Xilinx/qemu#4]
Hello,

We are using the Zynq chip at my company.  I am trying to set up user mode Qemu emulation using the Xilinx Qemu source so we can test our software before we put it on the instrument.  User mode emulation allows me to run arm binaries natively on the command line without booting an emulated box.  I have been successful doing this with the standard Qemu source, but I get an error when compiling the Xilinx Qemu source.  Here are the details.
I am building xilinx-master base on this document:
 http://www.wiki.xilinx.com/QEMU

I use this configure command

./configure --target-list=arm-linux-user --prefix=/usr/local --disable-bsd-user --disable-linux-aio --disable-kvm --disable-xen --static

and then "make"

with the standard qemu source I get a binary "qemu-arm" and I can use it in user mode to natively run some basic arm binaries as shown here:

root@catone-build-vm:~# file /usr/local/bin/arm-hello
/usr/local/bin/arm-hello: ELF 32-bit LSB executable, ARM, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=0xa8e22e289586b839763300626c20a415cc7ade4c, stripped
root@catone-build-vm:~# arm-hello
Hello, world!

When I run the same configure and make using the Xilinx Qemu source, I get this error

target-arm/helper.o: In function `pmccntr_read':
/opt/xilinx-qemu/qemu/target-arm/helper.c:341: undefined reference to `vm_clock'
/opt/xilinx-qemu/qemu/target-arm/helper.c:341: undefined reference to `qemu_get_clock_ns'
collect2: ld returned 1 exit status
make[1]: *** [qemu-arm] Error 1
make: *** [subdir-arm-linux-user] Error 2

**Comment by alistair23** [comment]
Unfortunately we don't support or test user mode emulation, which is why it isn't building. I will try to improve support in this area, but in the mean time you will have to use system emulation. I'm going to close this issue as it is very old. If this is still a problem with the newer release of QEMU please open up a new issue.
